### ISSUE TITLE
1st Week - Progress

### ISSUE THREAD

**Issue by dodoongtak** [CodeSoom/project-react-3-dodoongtak#1]
### 1. 이 앱을 언제 사용하나요?
- 내 인생 살날동안 얼마나 더 많은 돈을 벌어야 될지 확인 하고 싶을 때 사용합니다. 
 
### 2. 구체적인 사례는 무엇인가요?
- 사용자는 현재 나이, 자산, 그리고 연 수입을 입력합니다. 
- 사용자는 삶에 있어 자기가 꼭 이루고 싶은 옵션을 선택해야 됩니다. (옵션 갯수 미정)
   - 결혼
   - 자녀의 숫자
   - 집 ( 지역 해외 국내 / 수도권 혹은 지방 / 평수 )
   - 교육
   - 취미 (운동, 책, 각종 액티비티)
   - 교통 혹은 자가용 ( 외제차, 국산차)
   - 보험
   - 죽고 싶은 나이 혹은 경제적으로 은퇴하고 싶은 나이
   - etc... 
- 1번과 2번의 입력을 토대로, 앞으로 목표하는 라이프 스타일을 이루기 위해 돈을 얼마나 더 벌야 되는지 확인 할 수 있습니다.
  - 한달 기준 얼마를 더 벌어야되는지,
  - 1년 기준 얼마를 더 벌어야되는지,
  - 10년 기준 얼마를 더 벌어야되는지,

### 3. 이번주가 지나면 사용자는 무엇을 할 수 있나요?
- Landing Page((서비스의 첫 인상)을 볼 수 있습니다.  

### 4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- Landing Page 
- github page 배포

### 5. 이 서비스를 제작 할려는 의도가 무엇인가요?
- 원하는 삶을 이루기 위해, 현실적으로 필요한 돈을 보여줄려합니다.
- 결과를 보고, 현실자각을 하고, 본인의 삶의 목표를 어떻게 재설정 해야 될까, 
고민해보는 시간을 제공하는 서비스였으면 좋겠습니다.

### 6. 왜 이런 서비스를 기획했는가?
- 돈 !== 행복 but....

![image](https://user-images.githubusercontent.com/77006427/112001173-0dd43900-8b62-11eb-9358-250cd225ce5e.png)

![image](https://user-images.githubusercontent.com/77006427/112001146-06ad2b00-8b62-11eb-9160-05be14b891ff.png)

![image](https://user-images.githubusercontent.com/77006427/112001055-ebdab680-8b61-11eb-87cc-9a4383e569e7.png)

자본주의사회에 눈을 뜬 순간, 돈과의 인연을 뗼 수 없기에
( 물론... 있기야 하겠지만, 스님이 되어봅시다)  

내가 생각하는 행복을 이루기 위해서는 무슨 삶을 살고 싶을까?

목표로 하는 삶을 이루기 위해서는 얼만큼의 돈이 있어야 될까? 

이 두개의 간격에 대해 알고 싶어, 기획해보았습니다.

#### 일단 작게 첫 페이지를 제작해볼려합니다.
- 주제를 고민하고, 고민하다, 이제야 정해서 ㅎㅎㅎㅎㅎ 어떻게 구현 할 수 있을지는 차차 리서치해보면서 가볼려 합니다.
- 외부 서비스 적극 사용!

#### 이런 것도 볼 수 있으면 좋겠다~ 싶은 추가적인 기능이 생각나는게 있으시면 피드 주세요 ㅎㅎ 
- 예시) 그 돈을 벌려면 삼성전자 주식을 몇개를 들고 있어야되나, 금으로는 몇돈이 있어야 되는거냐, etc etc

**Comment by dodoongtak** [comment]
### 구체적인 사례를 이해하기 쉬운 시나리오

철수는 20대 후반 번듯한 직장에 다니고 있어요.

운이 좋아, 또래 친구들 보다 직장생활을 빠르게 시작했어요. 

벌어놓은 돈을 허튼 곳에 쓰지 않고, 무려 1억이라는 돈을 저축해놨어요! 

이제, 오랫동안 연애를 한 영희랑 결혼을 할려 합니다. 

그런데, 이제 미래에 대한 걱정이 이만저만이 아니에요. 

집이라던가, 자녀 계획이라던가, 꿈꾸고 있는 결혼 라이프 스타일이라던가, 그리고 자기가 원하는 앞으로의 미래...

"앞으로 얼만큼의 돈을 꾸준히 더 벌어야 되야되는지" 쓸데없는 생각을 하기 시작해요. 

이런데, 짜잔, 쇼미더머니(가제) 사이트를 발견해요.

원하는 라이프 스타일을 하기위해서는 얼만큼의 돈을 더 많이 벌어야되는지 
몇번의 정보 입력만으로 알려주는 사이트라고 해요!

철수는 자신의 정보를 입력했어요.

현재 나이는.. 20대 후반이고...
연봉은.. 3000 후반대 이고...
자산은... 1억....
 
그리고 앞으로 살아갈 삶에서 철수가 원하는 것을 고르기 시작해요...

- 집은 30평대 아파트 (서울 중심지에서 살짝 벗어나고 교통편이 그나마 수월한 강...강북?)
- 차는 국내 중형 차!
- 자녀는 아들 하나 딸 하나
- 한달 생활비는 200 정도...
- 보험비는 달에 100 정도...
- 은퇴는 65세에..

입력을 끝내고 이제 사이트에서 결과를 기다려보아요. 

와! 

## "철수님이 앞으로 더 벌어야 되는 돈은 30억입니다"

## "연 8500만 원"

## "월 720만 원"

## "일 24만원"

## "수입을 올리셔야 원하시는 라이프 스타일을 누릴 수 있으십니다"

철수는 가만히 모니터를 바라봐요.

열심히 살았는데, 열심히 살지 않다고 느껴지네요. 

24시간동안 일만해서 벌면 벌겠지만, 과연 저것들을 누리기위해, 자기의 삶이 없어지지 않을 까 생각해요.

아버지를 떠올려봅니다. 

철수는 이제 다시 자기가 원하는 라이프 스타일을 조정을 해보아요. 

비록 처음보다, 원하는 라이프스타일은 아니지만,
행복이 더 있는 라이프 스타일이라는 믿음이 생겨요. 

자신이 원하는 삶을 위해 얼마나 벌어야되는지를 지인들에게 공유해서 알려줘요. 

되도 않되는 대화들이 이어지네요.

내일 일찍 출근해야되니, 철수는 핸드폰을 끄고 자러갑니다.

**Comment by Kihyun92** [comment]
전반적인 서비스의 방향점, 의도 등을 잘 알려주신 것 같아요 👍🏼  무엇보다 아이디어가 굉장히 관심이 가네요 🤑 

다만, 이번주 일요일까지 형탁님이 구상하신 서비스의 핵심 가치를 어떻게하면 고객에게 전달 할 수 있을까요? 🤔
소개 페이지도 가치를 전달할 수 있는 방법일 수 있죠. 하지만 단순한 소개페이지보다는 메일을 전달하는게 더 빠를 것 같기도 해요. 

구상하신 서비스의 가장 중요한 가치가 무엇인지 생각해보시고, 그 핵심 가치를 아주 빠르게 전달해서 사용자들이 어떻게 생각하는지 피드백을 얻고 그 피드백을 통해 다시 가다듬어서 프로젝트를 완성해보는데 집중해보셔도 좋을 것 같습니다~

![agile](https://user-images.githubusercontent.com/35797540/112160111-34ab7180-8c2d-11eb-98a6-85218befb1d8.png)

**Comment by Kihyun92** [comment]
마치 제얘기같아서 눈물이.. 😭

빨리 써보고 싶은 서비스네요. 기대됩니다 👍🏼

**Comment by dodoongtak** [comment]
[칸반보드 활용](https://github.com/CodeSoom/project-react-3-dodoongtak/projects/1)

@Kihyun92 팀에서도 칸반보드 활용하시나요? ㅎㅎㅎ

이슈에 1주차 플랜 남기는것 보다 이렇게 tracking 하는게 더 좋을거라 생각되서 만들어봤어요.

**Comment by Kihyun92** [comment]
넵 JIRA의 칸반 보드를 이용합니다 ㅎㅎ

github - project 를 활용하는 것도 좋은 것 같아요 👍🏼
