### ISSUE TITLE
UX/UI 피드백

### ISSUE THREAD

**Issue by moonkii** [CodeSoom/project-react-3-dodoongtak#102]
서비스의 관점에서 첫 화면에 프로필 작성과 아파트 목록 보기 항목이 1:1 비율로 구성되어 있어서 처음봤을 때 메뉴를 고르는 고민도 해야하고, 기능상 아파트 목록보기가 핵심인 것 같은데 프로필 작성이 왜이렇게 강조되어 있지? 생각이 들어요.

제 개인적인 의견으로는 우리가 검사 같은거 할때 검사 시작 -> 프로필 작성 -> 검사 응답 -> 검사 결과보기 이런식으로 진행하듯이
아파트목록 보기(핵심기능) -> 프로필 없으면 프로필 작성 있으면 패스 -> 아파트 목록 -> 결과 이런식으로 보여주면 어떨까요??
프로필은 꼭 필요하긴 하지만 매번 사용하는 것도 아닌 것 같아서 작은 메뉴로 뺴서 관리해도 괜찮을 것 같아요.

**Comment by dodoongtak** [comment]
@moonkii 

사용자가 한강뷰 클릭 시 바로 폼을 입력하기 보다는 일단 아파트를 둘러보는 선태권을 우선 시 하였습니다. 

구경 우선!

구경 후 원하는 아파트를 구매를 원할 때 
사용자의 프로필을 입력하게 하는게 좋다고 판단하였습니다. 

P.S 
우선 기환님이 말씀해주신대로 구현하고 사용을 해봤는데,
한강뷰 아파트 알아보기를 눌렀는데 뭐를 입력을 하라하네? 라는 의문이 사용자가 생각 할 수도 있을 수도 있겠다 싶어서, 
아파트 구경은 프로필도 없이 할 수 있는게 아무래도 사용자가 서비스를 체험 할 수 있게 하지 않나 싶었습니다.

한강 뷰 알아보기? -> 아파트 보여줌 -> 아파트 구매? -> 구매할려면 사용자 저축 및 잔고 입력 -> 결과 

😄😄😄 

프로필 페이지로 갈 수 있는 Feature는 나중에 추가적인 엔터테이먼트 요소가 추가 될 떄 추가하기로 결정했습니다. 
(예시) 페라리를 살려면?
