### ISSUE TITLE
gh-page not working after installing react dependencies.

### ISSUE THREAD

**Issue by dodoongtak** [CodeSoom/project-react-3-dodoongtak#13]
#7 리액트 패키지 설치 후 조정 할 떄[ webpack에 dev mode를 추가한 이 후,](https://github.com/dodoongtak/show-me-the-money/blob/2cad003573af9442be0c0b64fe77983c319ed57c/package.json) 자동배포가 중단되었습니다.

![image](https://user-images.githubusercontent.com/77006427/112717459-2fea0480-8f30-11eb-9093-9efd2e6e2506.png)

어는 설정 부분 때문에 막혔는지, dev mode 추가 때문이지 않을 까 싶은데...

해당 dev mode를 제거를 하면 webpack에서 mode warning이 지속적으로 나옵니다. 

아니면 혹은.. ci 쪽이 문제인것인데 따로 이상한점은 확인되지않습니다. #11 d2efa43b961d4b670158f5f140c797d4bca7cf36

문제의 발단 및  해결방안에 대해 피드를 요청합니다.

**Comment by Kihyun92** [comment]
`index.html`의 body tag 안에 `<script src="/main.js"></script>`를 추가해보실 수 있나요?

**Comment by Kihyun92** [comment]
아 아닐 것 같네요. 이미 gh-pages 브랜치에 index.html에 헤더에 defer로 스크립트를 가져오고 있었군여 🤔 

https://github.com/CodeSoom/project-react-3-dodoongtak/blob/32039aa5e1049f77e188961b5505b3c11de1e208/index.html#L8

**Comment by dodoongtak** [comment]
react 설치 커밋 이 후, gh-pages에서 [deploy](https://github.com/CodeSoom/project-react-3-dodoongtak/commit/32039aa5e1049f77e188961b5505b3c11de1e208) 도 중 CNAME을 삭제시켜 발생한 문제. 

![image](https://user-images.githubusercontent.com/77006427/112729305-d1904680-8f6e-11eb-8caa-c9508fa14bdb.png)

Custom domain 재 설정 / CNAME 재생성 하여 해결 완료.

**Comment by dodoongtak** [comment]
![image](https://user-images.githubusercontent.com/77006427/113141650-eb7aa380-9264-11eb-8b04-ee5abf180030.png)


매 merge 후, 설정 해놓은 CNAME이 삭제 됩니다. 

static에 고정으로 들어가 있지 않아 발생하는 문제라 예상. 

![image](https://user-images.githubusercontent.com/77006427/113141492-bb330500-9264-11eb-8e86-2384e231b3f7.png)

**Comment by dodoongtak** [comment]
WIP

현재 시도한 방법들 

1. gh page branch에 수동으로 CNAME 추가.  ❌ 
2. public folder(static folder)에 CNAME 추가하여 PR & MERGE ❌
