### ISSUE TITLE
2nd Week 🤪

### ISSUE THREAD

**Issue by dodoongtak** [CodeSoom/project-react-3-dodoongtak#21]
1주 차 플랜에, 아이디어를 크게 크게 잡다보니, 세분화가 부족했습니다.

기획은 항시 변경되는걸로! 

원래 기획에 타협해서 작게 하는게 아닌,
1주일이라는 주어진 시간에, 구현이 가능한 기획으로 구성을 했어야되는게,
'작게 작게 하라의 뜻'.

작게 작게가 코드를 베이스부터 만들라는게 아님. 

작게 작게 기능을 만들어야, 피드를 받아서, 차 주에 빠른 변경이 가능. 
작성한 코드를 버릴 때도 미련 없이 폐기 할 수 있음.

1주일 안에 구현 할 수 있는 기획으로! 

최소한의 기능명세서를 작성을 우선! 

※ 1주 차 진행 도 중 정체성이 없어서 급유턴이 발생.

**Comment by moonkii** [comment]
네 잘 이해하고 계신 것 같아요. 👍 
작게 할 수록 기획이 변경되더라도 유연하게 대처가 가능해요.

**Comment by dodoongtak** [comment]
[1주 차 계획](https://github.com/CodeSoom/project-react-3-dodoongtak/issues/1#issue-837752855)이였던 것.. ㅎ  
큰 틀이였기에 기회가 될 수 있을 떄 마다 매 주 차에 기능 추가 예정.
이 아이디어의 기획의도는 1주차에 기입했습니다. 
5번 6번을 참고해주세요. 

## 2주 차 

### 1. 이 앱을 언제 사용하나요? 
- 꿈의 아파트에 살려면 돈을 얼마나 더 벌어야되는지 알려드립니다. 

### 2. 구체적인 사례는 무엇인가요?
- 사용자는 이름, 현재 나이, 자산, 그리고 연 수입을 입력합니다.
- 살고싶은 아파트를 선택합니다. 
   - 5가지의 유형 중 하나를 선택합니다.
      - 1. 한강뷰
      - 2. 강남
      - 3. 조경 우수
      - 4. 주변 상권 우수
      - 5. 재건축
    - 해당 유형에 아파트 4개 중 하나를 선택합니다. 
- 선택한 아파트의 최근 매매가격에 기반하여, 얼마나 더 벌어야되는지에 대한 결과를 확 인 할 수 있습니다. 

비쥬얼로 이해하기 쉽도록 와이어프레임을 제작해봤습니다. 
([와이어프레임 링크](https://whimsical.com/hmm-6jFmt6U1itwUWAACdViT71@VsSo8s35WwPAnCfbRkEiBt))를 확인해주세요.  

※디자인은 우선 고려 안했습니다. 
현재 귀하신 디자이너분을 이 누추한 프로젝트에 모실 수 있는 지 물색중...
디자이너분들이랑 연이 없네요 ㅎㅎ

### 3. 이번 주가 지나면 사용자는 무엇을 할 수 있나요? 
- 내 정보를 통해, 꿈의 아파트에 살려면 얼머나 돈을 더 벌어야 되는 지 알 수 있습니다.

### 4. 이번 주 에 구현 할 기능을 우선 순위대로 작성 해주세요.
- 내 정보 편집
- 아파트 선택 스크린
- 결과 스크린

### 5. 이번 주 코드 퀄리티를 위한 셀프리뷰 체크리스트

#### PR 전 코드 리뷰
- [ ] 구현 완료 후 주석을 제거 했는가?
- [ ] test 파일을 우선 작성했는가?
- [ ] destrucuting을 했는가?
- [ ] condition이 복잡한가?
- [ ] 중복되는 logic을 refactoring 했는가?
- [ ] 기존에 사용할 수 있는 resource를 활용했는가?
- [ ] 관심사 분리가 되어있는가? 
- [ ] 최적화가 필요하지 않은곳에 최적화를 썼는가?

#### [커밋 셀프 리뷰](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/) 
- [ ] TMI 금지. 
- [ ] 코드로 알 수 있는 내용은 분문에 포함하지 않기.
- [ ] 명확한 의도가 있는 커밋 메세지
- [ ] 무엇인지 모르겠으면, 극단적으로 커밋 메세지를 우선 작성 하여, 구분

#### Merge 전 셀프 리뷰
- [ ] 1 commit per PR 이지만, 해당 커밋에 정말 필요한 코드가 없으면 추가 하여아함.
- [ ] 혹시나 코드리뷰에 빠드린 부분이 있을 수 있으니, 다시 한번 정밀 검사.
- [ ] 내 손가락 믿지 않기. 

### 6. PROJECT & ISSUE 제대로 활용하기
- 지금 현재 이 이슈에 무엇을 할지 적는게 아닌, 오늘 하루 무엇을 코드를 해야 될지 PROJECT에 [칸반보드](https://github.com/CodeSoom/project-react-3-dodoongtak/projects/1)에 작성.  
- 질문은 PR이 아닌 Issue 에 남긴다. 
- 필요한 label은 그떄 그때 넣는다. 

## 제일 이루고 싶은 목표
작게 작게, 가능한 대로 유연하게 대처해서 진행하기~

**Comment by moonkii** [comment]
디자인은 제일 마지막에 붙일 수도 있어요.
오히려 디자이너와 함께할 경우 프로젝트를 다 보여주고 의도를 확인하고 완성된 형태를 직접 볼 수 있어서 디자인하기가 더 좋죠.

아직 아이디어가 정해지지 않았고, 방향을 정해가는 시기라면 정말 간단하고 빠르게 
정보입력 -> 정말 단순한 선택(select 나 check 혹은 입력도 상관없음)  -> 결과 화면(단순 텍스트라도 상관없음)
정도로 완성해보고 피드백도 받아보고 하면 좋을 것 같아요.
