### ISSUE TITLE
README를 꾸며주세요~

### ISSUE THREAD

**Issue by Kihyun92** [CodeSoom/project-react-3-dodoongtak#3]
구상하신 서비스가 어떤 서비스인지, 그리고 어떻게 사용할 수 있을지 알 수 있도록 간단하게 작성 해주면 좋을 것 같아요.

**Comment by dodoongtak** [comment]
우선, 이전 진행 됬던 레포 기반으로 간략하게 작성했습니다. 

화면 구성 및 스크립트 관련되서 보강 하여 업데이트 진행하도록 하겠습니다. 🤐
