### ISSUE TITLE
3rd Week 🤦‍♀️

### ISSUE THREAD

**Issue by dodoongtak** [CodeSoom/project-react-3-dodoongtak#47]
### 1. 이 앱을 언제 사용하나요? 
- 꿈같은 아파트에 살려면 얼마나 걸리는지 확인 할 수 있습니다. 

#### 사용자는 
- 이름, 나이, 월 저축, 그리고 은행잔고를 입력 할 수 있습니다.
- 살고싶은 아파트를 선택 할 수 있습니다. 
   - 2가지의 아파트 유형 중 하나를 선택합니다.
      1. 한강뷰
      2. 주변 상권 우수
   - 선택한 유형의 아파트들을 볼 수 있습니다.
      - 아파트 정보
        1. 이름 
        2. 평수
        3.  지역
- 선택한 아파트를 구매할려면 얼마나 걸리는지 확인할 수 있습니다.
    - 아파트 가격 및 부가적인 정보
      1. 아파트 이름
      2. 평수 X -> m^2 로 고정 ( 2007년 정부에서 제곱미터로 시정 ※평은 일제강점기 잔여물)
      3. 가격
      4. 지역
      5. 지번
    - 아파트 구매까지에 대한 종합 정보 
      1. 필요한 금액
      2. 소요 기간
      3. 구매 시 나이 

### 3. 이번 주가 지나면 사용자는 무엇을 할 수 있나요? 
- 사용자 친화적인 UI/UX로 사이트를 사용 할 수 있습니다.
- 꿈같은 아파트를 구매할려면, 걸리는 기간을 확인 할 수있습니다.

### 4. 이번 주 에 구현 할 기능을 우선 순위대로 작성 해주세요.
1. 연봉/자산 -> 월 저축/ 현재까지 저축금액 으로 변경
2. MAKE IT BEAUTIFUL (MOBILE FIRST) -> 4주차로 이전 ㅎ

### 고민되는 부분
- 넘 이과라 문구 작성이 어색합니다. 예시) 내 정보 입력하기 X <- 넘 딱딱s..
- 디자인 감각이 현저히 떨어져, 구현 할 수 있는 디자인이 감이 잡히지않습니다. 
기현님은 보통 어떻게 진행하시나요? 토이프로젝트 진행 시  
(원하는 UI는 많지만... 디자인적으로 맞는가... THEME... LOGO... WOW)

**Comment by Kihyun92** [comment]
문구 작성이 어렵다면 구어체와 같이 해보는 것도 방법일 것 같아요 ㅎㅎ 토스를 참고해봐도 좋을 것 같습니다~

저도 디자인은 꽝이라😅 답변이 될지 모르겠지만, 가능하면 요즘 인기있는 앱들을 참고하려 합니다.(토스, 컬리, 오늘의집, 뱅크셀러드 등등 많은것 같아요)

**Comment by dodoongtak** [comment]
@Kihyun92 

기현님 최근에 UI 한글 텍스트에 대한 RIDI(책서비스) 쪽에서 정리한 디자인 시스템  내용을 읽다가, 이전에 구어체에 관해 나눈 대화 내용이 기억나서 남겨봅니다. ㅎㅎ 😱 


목차:
1. 사용자 입장 생각하며 쓰기
2. 간결하고 쉽게 쓰기
3. 일관선 있게 쓰기
4. 신뢰성 있게 쓰기

- 기타 텍스테에 관한 포맷


[리디 디자인 시스템 - UI 한글 텍스트](https://ridi.design/writings/#ui-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%9E%91%EC%84%B1-%EA%B8%B0%EB%B3%B8-%EC%9B%90%EC%B9%99)


영문은... 
아마존은 이리 [가이드라인](https://developer.amazon.com/en-US/docs/alexa/alexa-auto/ui-text-guidelines.html
)을 제시 하네요 🤯 

[구글 가이드라인](https://material.io/design/communication/writing.html#principles)

기현님 사측에서는 UI text는 디자이너에게 권한을 일괄 부여하시나요?

**Comment by Kihyun92** [comment]
> @Kihyun92
> 
> 기현님 최근에 UI 한글 텍스트에 대한 RIDI(책서비스) 쪽에서 정리한 디자인 시스템 내용을 읽다가, 이전에 구어체에 관해 나눈 대화 내용이 기억나서 남겨봅니다. ㅎㅎ 😱
> 
> 목차:
> 
> 1. 사용자 입장 생각하며 쓰기
> 2. 간결하고 쉽게 쓰기
> 3. 일관선 있게 쓰기
> 4. 신뢰성 있게 쓰기
> 
> * 기타 텍스테에 관한 포맷
> 
> [리디 디자인 시스템 - UI 한글 텍스트](https://ridi.design/writings/#ui-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%9E%91%EC%84%B1-%EA%B8%B0%EB%B3%B8-%EC%9B%90%EC%B9%99)
> 
> 영문은...
> 아마존은 이리 [가이드라인](https://developer.amazon.com/en-US/docs/alexa/alexa-auto/ui-text-guidelines.html)을 제시 하네요 🤯
> 
> [구글 가이드라인](https://material.io/design/communication/writing.html#principles)
> 
> 기현님 사측에서는 UI text는 디자이너에게 권한을 일괄 부여하시나요?

문구는 주로 프로덕트 팀 분들(PM, 운영, 디자인) 분들이 가이드 합니다 ㅎㅎ 물론 기획 리뷰 단계나 개발 과정 중에 기획자분들과 협의를 하면서 문구를 수정 되기는 해요 ㅎㅎ

아직 저희 회사도 디자인 시스템이 잡혀있지는 않지만, 팀 내에서도 조금씩 논의되고 있긴합니다. 좋은 자료 공유 감사합니다~
